on:
  push:
    tags:
      - 'v0.*'
name: Build and Tag Release
jobs:
  build:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: 'docker/login-action@v1'
        name: 'Docker Login'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get Release Tag
        id: tag
        uses: dawidd6/action-get-tag@v1
      - name: Build Images
        run: make build
      - name: Tag Images
        run: docker images | grep connamara/ | grep latest | awk '{print $1}' | awk -F/ '{print $2}' | xargs -I % docker tag connamara/%:latest ghcr.io/connamara-tech/%:${{steps.tag.outputs.tag}}
      - name: Push Images
        run: docker images | grep connamara-tech/ | grep ${{steps.tag.outputs.tag}} | awk '{print $1}' | xargs -I % docker push %:${{steps.tag.outputs.tag}}